from prometheus_client import Counter, Histogram


TRADES_GENERATED_TOTAL = Counter(
    "trades_generated_total",
    "Total number of trade events generated by the producer",
    labelnames=["symbol"],
)


TRADES_PUBLISHED_TOTAL = Counter(
    "trades_published_total",
    "Total number of trade events successfully published to Kafka",
    labelnames=["symbol", "topic"],
)


PRODUCER_PUBLISH_FAILURES_TOTAL = Counter(
    "producer_publish_failures_total",
    "Total number of Kafka publish failures",
    labelnames=["failure_type"],
)


PRODUCER_ENQUEUE_DURATION_SECONDS = Histogram(
    "producer_enqueue_duration_seconds",
    "Time spent enqueueing a trade event in the Kafka producer",
)