services:
  kafka-ui:
    image: provectuslabs/kafka-ui:latest

    ports:
      - "8080:8080"

    environment:
      KAFKA_CLUSTERS_0_NAME: market-data-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      DYNAMIC_CONFIG_ENABLED: "true"

    depends_on:
      kafka:
        condition: service_healthy

    networks:
      - market-data-network

    restart: unless-stopped